---
Name: goldfinch-component-reviews
---

Goldfinch\Component\Reviews\Admin\ReviewsAdmin:
  extensions:
    - Goldfinch\Helpers\Extensions\BlocksAdminExtension

---
Name: goldfinch-component-reviews-icon
Only:
  moduleexists: 'goldfinch/enchantment'
---

Goldfinch\Component\Reviews\Admin\ReviewsAdmin:
  menu_icon_class: 'bi-chat-square-quote-fill'

Goldfinch\Component\Reviews\Admin\Blocks\ReviewsBlock:
  icon: 'bi-chat-square-quote-fill'


